### ISSUE TITLE
Can't open thread dumps with deadlock due to monitor loop

### ISSUE THREAD

**Issue by vigevenoj** [vigevenoj/tda#2]
Fails with this stack trace,
LT-A9-121149:Downloads jacob.vigeveno$ java -jar ~/tools/tda-bin-2.2/tda.jar 
Exception in thread "Thread-3" java.lang.IllegalArgumentException: new child is an ancestor
    at javax.swing.tree.DefaultMutableTreeNode.insert(DefaultMutableTreeNode.java:179)
    at com.pironet.tda.SunJDKParser.renormalizeBlockingThreadTree(SunJDKParser.java:819)
    at com.pironet.tda.SunJDKParser.dumpBlockingMonitors(SunJDKParser.java:758)
    at com.pironet.tda.SunJDKParser.parseNext(SunJDKParser.java:347)
    at com.pironet.tda.SunJDKParser.hasMoreDumps(SunJDKParser.java:76)
    at com.pironet.tda.TDA.addThreadDumps(TDA.java:1337)
    at com.pironet.tda.TDA.access$1500(TDA.java:132)
    at com.pironet.tda.TDA$4.construct(TDA.java:930)
    at com.pironet.tda.utils.SwingWorker$2.run(SwingWorker.java:131)
    at java.lang.Thread.run(Thread.java:745)

**Comment by vigevenoj** [comment]
https://java.net/projects/tda/lists/commits/archive/2011-09/message/3 might have some details
